services:
  svelte-app:
    build:
      context: ./3Rhack
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    command: npm run dev
    networks:
      - app-network

  python-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - svelte-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge